### PR TITLE
enable vendor as the highest priority import path

### PR DESCRIPTION
**Pull request by ycliuhw**
parse into `srcDir` to enable `vendor` as highest priority import path

### CODE REVIEW

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
:shipit:

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by Veebers** [comment]
$$merge$$

**Pull request merged**
