### PR TITLE
httptesting: maintain seekerness of body

### PR DESCRIPTION
**Pull request by rogpeppe**
This allows us to put a seekable body into AssertJSONCall and
later retrieve it for use with custom Do methods that require
a seekable reader.

(Review request: http://reviews.vapour.ws/r/1448/)

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by frankban** [comment]
:+1: ty!

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Pull request merged**
